/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulator;

import javax.swing.JOptionPane;

/**
 *
 * @author mac
 */
public class FrmKalkulator extends javax.swing.JFrame {
    
    private Double temp1, temp2;
    private String operator = "";
    
    /**
     * Creates new form FrmKalkulator
     */
    public FrmKalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layar = new javax.swing.JLabel();
        satu = new javax.swing.JButton();
        dua = new javax.swing.JButton();
        tiga = new javax.swing.JButton();
        empat = new javax.swing.JButton();
        empat1 = new javax.swing.JButton();
        tiga1 = new javax.swing.JButton();
        dua1 = new javax.swing.JButton();
        satu1 = new javax.swing.JButton();
        same = new javax.swing.JButton();
        clean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        layar.setBackground(new java.awt.Color(0, 204, 204));
        layar.setForeground(new java.awt.Color(51, 51, 255));
        layar.setText("0");

        satu.setText("1");
        satu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                satuMouseClicked(evt);
            }
        });

        dua.setText("2");
        dua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                duaMouseClicked(evt);
            }
        });
        dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duaActionPerformed(evt);
            }
        });

        tiga.setText("3");
        tiga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tigaMouseClicked(evt);
            }
        });
        tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigaActionPerformed(evt);
            }
        });

        empat.setText("4");
        empat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empatMouseClicked(evt);
            }
        });
        empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empatActionPerformed(evt);
            }
        });

        empat1.setText("/");
        empat1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empat1MouseClicked(evt);
            }
        });
        empat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empat1ActionPerformed(evt);
            }
        });

        tiga1.setText("x");
        tiga1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tiga1MouseClicked(evt);
            }
        });
        tiga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiga1ActionPerformed(evt);
            }
        });

        dua1.setText("-");
        dua1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dua1MouseClicked(evt);
            }
        });

        satu1.setText("+");
        satu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                satu1MouseClicked(evt);
            }
        });

        same.setText("=");
        same.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sameMouseClicked(evt);
            }
        });
        same.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sameActionPerformed(evt);
            }
        });

        clean.setText("C");
        clean.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cleanMouseClicked(evt);
            }
        });
        clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(same, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clean, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(layar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(satu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dua, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tiga, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(empat, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(satu1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dua1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tiga1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empat1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(layar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(satu)
                    .addComponent(dua)
                    .addComponent(tiga)
                    .addComponent(empat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(satu1)
                    .addComponent(dua1)
                    .addComponent(tiga1)
                    .addComponent(empat1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(same)
                    .addComponent(clean))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layar.getAccessibleContext().setAccessibleName("layar");
        satu.getAccessibleContext().setAccessibleName("satu");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tigaActionPerformed

    private void empatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empatActionPerformed

    private void satuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_satuMouseClicked
        // TODO add your handling code here:
        masukLayar(satu);
    }//GEN-LAST:event_satuMouseClicked

    private void empat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empat1ActionPerformed

    private void tiga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiga1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiga1ActionPerformed

    private void satu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_satu1MouseClicked
        // TODO add your handling code here:
        // tombol kali
        //sebelum layar dihilangkan simpan datanya
        String l = layar.getText();
        temp1 = Double.parseDouble(l);
        //ketika tombol kali di klik maka layar kosong
        layar.setText("");
        operator = satu1.getText();
    }//GEN-LAST:event_satu1MouseClicked

    private void sameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sameActionPerformed

    private void duaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duaActionPerformed

    private void duaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_duaMouseClicked
        // TODO add your handling code here:
        masukLayar(dua);
    }//GEN-LAST:event_duaMouseClicked

    private void tigaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tigaMouseClicked
        // TODO add your handling code here:
        masukLayar(tiga);
    }//GEN-LAST:event_tigaMouseClicked

    private void empatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empatMouseClicked
        // TODO add your handling code here:
        masukLayar(empat);
    }//GEN-LAST:event_empatMouseClicked

    private void sameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sameMouseClicked
        // TODO add your handling code here:
        if( !operator.equals("") ){
            String lyr = layar.getText();
            if( !lyr.equals("") ){
                Double hasil;
                temp2 = Double.parseDouble( lyr );
                switch( operator ){
                    case "+":
                        hasil = temp1 + temp2;
                        layar.setText( hasil.toString() );
                        break;
                    case "-":
                        hasil = temp1 - temp2;
                        layar.setText( hasil.toString() );
                        break;
                    case "x":
                        hasil = temp1 * temp2;
                        layar.setText( hasil.toString() );
                        break;
                    case "/":
                        hasil = temp1 / temp2;
                        layar.setText( hasil.toString() );
                        break;
                }
            }else{
                JOptionPane.showMessageDialog(null, "Masukan angka terlebih dahulu");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Masukan operator terlebih dahulu");
        }
    }//GEN-LAST:event_sameMouseClicked

    private void cleanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cleanMouseClicked
        // TODO add your handling code here:
        layar.setText("0");
        operator = "";
        temp1 = 0.0;
    }//GEN-LAST:event_cleanMouseClicked

    private void cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cleanActionPerformed

    private void dua1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dua1MouseClicked
        // TODO add your handling code here:
        //sebelum layar dihilangkan simpan datanya
        String l = layar.getText();
        temp1 = Double.parseDouble(l);
        //ketika tombol kali di klik maka layar kosong
        layar.setText("");
        operator = dua1.getText();
    }//GEN-LAST:event_dua1MouseClicked

    private void tiga1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tiga1MouseClicked
        // TODO add your handling code here:
        //sebelum layar dihilangkan simpan datanya
        String l = layar.getText();
        temp1 = Double.parseDouble(l);
        //ketika tombol kali di klik maka layar kosong
        layar.setText("");
        operator = tiga1.getText();
    }//GEN-LAST:event_tiga1MouseClicked

    private void empat1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empat1MouseClicked
        // TODO add your handling code here:
        //sebelum layar dihilangkan simpan datanya
        String l = layar.getText();
        temp1 = Double.parseDouble(l);
        //ketika tombol kali di klik maka layar kosong
        layar.setText("");
        operator = empat1.getText();
    }//GEN-LAST:event_empat1MouseClicked
    
    public void masukLayar(javax.swing.JButton btn){
        String lyr = layar.getText();
        String a = btn.getText();
        lyr = lyr.equals( "0" ) ? "" : lyr;
        lyr += a;
        layar.setText( lyr );
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmKalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clean;
    private javax.swing.JButton dua;
    private javax.swing.JButton dua1;
    private javax.swing.JButton empat;
    private javax.swing.JButton empat1;
    private javax.swing.JLabel layar;
    private javax.swing.JButton same;
    private javax.swing.JButton satu;
    private javax.swing.JButton satu1;
    private javax.swing.JButton tiga;
    private javax.swing.JButton tiga1;
    // End of variables declaration//GEN-END:variables
}
